### ISSUE TITLE
The issue of image not found

### ISSUE THREAD

**Issue by babyfish0226** [fotiDim/Romo#15]
I try to build Romo X and after lots of works i got the error below:

dyld: Library not loaded: @rpath/RMShared.framework/RMShared
  Referenced from: /var/containers/Bundle/Application/243DC462-305F-436B-90D8-A9FE836408AA/Romo.app/Romo
  Reason: image not found

Any suggestions? Thanks.

update:
After i add the frameworks back to Embed Frameworks and got the error below:
Cound not inspect the applicatin package.

I found it's very hard to build this project and i had bought romo X app from app store.

**Comment by fotiDim** [comment]
@babyfish0226 this sounds like a dynamic framework issue. It shouldn't be a problem anymore as we have migrated to CocoaPods. Just pull the latest changes, and run `pod install`. Closing down this issue as it is not relevant with anymore since we migrate to CocoaPods. Feel free to reopen if you still have a problem.

**Comment by fotiDim** [comment]
@babyfish0226 there is a new [Romo Pod](https://cocoapods.org/pods/romo) out!
It should be super easy to use the Romo SDK from now on. Thanks for the feedback!
