### ISSUE TITLE
Did You Ever Open Your Romo

### ISSUE THREAD

**Issue by bwake2012** [fotiDim/Romo#23]
I have a Romo that won't hold a charge. I would like to take a look at the battery pack, to see if it could be replaced. I saw your note on the YouTube video [Take Me to Your Leader](https://youtu.be/RvBQ9tYP9E4). Did you ever get it open?

More importantly, did you get it back together, and does it work?

**Comment by fotiDim** [comment]
Check [this](https://github.com/Navideck/Romo/wiki/Disassemble-Romo) wiki entry for instructions on how to disassemble Romo.

To be honest I didn't bother assembling it back but it works fine in the disassembled form. I keep it this way because I want to experiment on it occasionally. It should be trivial to put it back together.

**Comment by bwake2012** [comment]
Thanks for your reply.

It turns out to be sensitive to which charger is used with it. It charged after I plugged it into a different charger.

I got group activities working with it.

**Comment by bwake2012** [comment]
Thanks for the wiki link.
